paths:
  processed_dir: "data/processed"
  models_dir: "models"

data:
  tournament: "uel"
  dataset_filename: "train.parquet"

training:
  target_column: "target"

  # Укажи свои 2 лаговые фичи из processed
  feature_columns:
    - "points_diff_lag1"
    - "points_total_lag1"

  test_size: 0.2
  random_state: 42
  stratify: true

  # Если есть колонка даты/времени — позже можно сделать time-split.
  # Сейчас оставляем random split.
  time_column: null

model:
  name: "catboost_baseline"
  type: "catboost"
  save_format: "cbm"

  params:
    loss_function: "Logloss"
    eval_metric: "AUC"
    iterations: 300
    learning_rate: 0.05
    depth: 6
    l2_leaf_reg: 3.0

    # Важно для скорости/стабильности
    random_seed: 42
    verbose: 100
    allow_writing_files: false

    # Ранний стоп по валидации
    od_type: "Iter"
    od_wait: 200

logging:
  level: "INFO"

hydra:
  run:
    dir: .
